project_id = "pgjyzayvkyrftcksvncj"

[functions.send-lead-magnet]
verify_jwt = false

[functions.draft-newsletter]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.newsletter-admin]
verify_jwt = false
