// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use to verify MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/brand-overview.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var OVERVIEW = `White Rabbit LA \u2014 luxury private magic and sophisticated event entertainment.
Founder: Scott Syme. Based in Los Angeles, performs nationwide.
Positioning: white-glove hospitality; magic performed WITH guests, never AT them.
Signature offerings: Cocktail-hour close-up, Private Magic Show, Speakeasy sets, Magic Mondays residency.
Booking lead time: 4\u20136 weeks (8\u201312 weeks peak season).
Contact: scott.syme@whiterabbitla.com \u2014 https://whiterabbitla.com`;
var brand_overview_default = defineTool2({
  name: "brand_overview",
  title: "Brand overview",
  description: "Returns a concise overview of White Rabbit LA \u2014 positioning, offerings, and contact info.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({ content: [{ type: "text", text: OVERVIEW }] })
});

// src/lib/mcp/tools/import-contacts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
var VALID_CATEGORIES = [
  "wedding_planner",
  "corporate_planner",
  "spirits",
  "resident",
  "dmc",
  "venue",
  "fundraiser",
  "trade_show",
  "golf_tournament",
  "charity_golf",
  "country_club",
  "pr_agency",
  "nonprofit",
  "talent",
  "restaurant",
  "nightlife",
  "luxury_auto",
  "tech_events",
  "hotel_concierge",
  "casino_entertainment"
];
var ROLE_BASED_PREFIXES = /* @__PURE__ */ new Set([
  "info",
  "hello",
  "contact",
  "events",
  "admin",
  "support",
  "sales",
  "team",
  "office",
  "help",
  "marketing",
  "no-reply",
  "noreply"
]);
var ContactSchema = z2.object({
  email: z2.string().describe("Email address (required)."),
  name: z2.string().optional(),
  first_name: z2.string().optional(),
  last_name: z2.string().optional(),
  company: z2.string().optional(),
  title: z2.string().optional(),
  phone: z2.string().optional(),
  city: z2.string().optional(),
  state: z2.string().optional(),
  linkedin_url: z2.string().optional(),
  apollo_id: z2.string().optional(),
  website: z2.string().optional(),
  domain: z2.string().optional(),
  notes: z2.string().optional()
});
var import_contacts_default = defineTool3({
  name: "import_contacts",
  title: "Import cold-outreach contacts",
  description: "Upload contacts scraped from Apollo (or similar) into a specific drip campaign category. Dedupes by email + apollo_id against existing campaigns, skips role-based addresses (info@, hello@, etc.) and anything on the suppression list. Contacts are inserted PAUSED by default \u2014 set start_immediately=true to enroll them in the drip right away. Returns a full breakdown of inserted vs skipped counts.",
  inputSchema: {
    campaign_category: z2.enum(VALID_CATEGORIES).describe("Which drip campaign these contacts belong to."),
    contacts: z2.array(ContactSchema).min(1).max(500).describe("Array of contacts (max 500 per call)."),
    start_immediately: z2.boolean().optional().describe("If true, contacts enroll in the drip immediately. Default false (paused).")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ campaign_category, contacts, start_immediately }) => {
    const supabase = createClient(
      // @ts-ignore Deno env at runtime
      globalThis.Deno?.env.get("SUPABASE_URL") ?? "",
      // @ts-ignore Deno env at runtime
      globalThis.Deno?.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );
    const seen = /* @__PURE__ */ new Set();
    const cleaned = contacts.map((c) => ({ ...c, email: (c.email || "").toLowerCase().trim() })).filter((c) => {
      if (!c.email || !c.email.includes("@")) return false;
      if (seen.has(c.email)) return false;
      seen.add(c.email);
      return true;
    });
    const skipped = [];
    const roleBased = [];
    const afterRole = cleaned.filter((c) => {
      const local = c.email.split("@")[0];
      if (ROLE_BASED_PREFIXES.has(local)) {
        roleBased.push({ email: c.email });
        skipped.push({ email: c.email, reason: "role_based" });
        return false;
      }
      return true;
    });
    if (roleBased.length) {
      await supabase.from("email_suppression_list").upsert(
        roleBased.map((r) => ({
          email: r.email,
          reason: "role_based",
          source_campaign_category: campaign_category,
          notes: "Auto-rejected via MCP import (role-based local-part)"
        })),
        { onConflict: "email", ignoreDuplicates: true }
      );
    }
    const emails = afterRole.map((c) => c.email);
    const { data: suppressed } = emails.length ? await supabase.from("email_suppression_list").select("email, reason").in("email", emails) : { data: [] };
    const suppMap = new Map((suppressed || []).map((r) => [r.email, r.reason]));
    const afterSupp = afterRole.filter((c) => {
      const r = suppMap.get(c.email);
      if (r) {
        skipped.push({ email: c.email, reason: `suppressed:${r}` });
        return false;
      }
      return true;
    });
    const apolloIds = afterSupp.map((c) => c.apollo_id).filter(Boolean);
    const existingEmails = /* @__PURE__ */ new Set();
    const existingApollo = /* @__PURE__ */ new Set();
    if (afterSupp.length) {
      const { data } = await supabase.from("cold_email_campaigns").select("email, apollo_id").in("email", afterSupp.map((c) => c.email));
      (data || []).forEach((r) => existingEmails.add(r.email));
    }
    if (apolloIds.length) {
      const { data } = await supabase.from("cold_email_campaigns").select("apollo_id").in("apollo_id", apolloIds);
      (data || []).forEach((r) => r.apollo_id && existingApollo.add(r.apollo_id));
    }
    const toInsert = [];
    for (const c of afterSupp) {
      if (existingEmails.has(c.email)) {
        skipped.push({ email: c.email, reason: "email_exists" });
        continue;
      }
      if (c.apollo_id && existingApollo.has(c.apollo_id)) {
        skipped.push({ email: c.email, reason: "apollo_id_exists" });
        continue;
      }
      const concatName = [c.first_name, c.last_name].filter(Boolean).join(" ").trim() || c.name || null;
      toInsert.push({
        email: c.email,
        name: concatName,
        first_name: c.first_name ?? null,
        last_name: c.last_name ?? null,
        company: c.company ?? null,
        title: c.title ?? null,
        phone: c.phone ?? null,
        city: c.city ?? null,
        state: c.state ?? null,
        linkedin_url: c.linkedin_url ?? null,
        apollo_id: c.apollo_id ?? null,
        website: c.website ?? null,
        domain: c.domain ?? null,
        notes: c.notes ?? null,
        campaign_category,
        status: start_immediately ? "active" : "paused",
        current_step: 0,
        started_at: start_immediately ? (/* @__PURE__ */ new Date()).toISOString() : null
      });
    }
    let inserted = 0;
    const errors = [];
    for (let i = 0; i < toInsert.length; i += 100) {
      const chunk = toInsert.slice(i, i + 100);
      const { data, error } = await supabase.from("cold_email_campaigns").insert(chunk).select("id");
      if (error) errors.push(`Chunk ${i}: ${error.message}`);
      else inserted += data?.length || 0;
    }
    const summary = {
      campaign_category,
      received: contacts.length,
      cleaned: cleaned.length,
      inserted,
      skipped_role_based: roleBased.length,
      skipped_suppressed: (suppressed || []).length,
      skipped_total: skipped.length,
      status: start_immediately ? "active" : "paused",
      errors: errors.length ? errors : void 0,
      skipped_detail: skipped.slice(0, 50)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }]
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "white-rabbit-la-mcp",
  title: "White Rabbit LA",
  version: "0.2.0",
  instructions: "Tools for the White Rabbit LA site. Use `echo` to verify connectivity, `brand_overview` for a brand summary, and `import_contacts` to upload Apollo-scraped contacts into a specific drip campaign category (dedupes + respects suppression list; inserted paused unless start_immediately=true).",
  tools: [echo_default, brand_overview_default, import_contacts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
