// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use to verify MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/brand-overview.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var OVERVIEW = `White Rabbit LA \u2014 luxury private magic and sophisticated event entertainment.
Founder: Scott Syme. Based in Los Angeles, performs nationwide.
Positioning: white-glove hospitality; magic performed WITH guests, never AT them.
Signature offerings: Cocktail-hour close-up, Private Magic Show, Speakeasy sets, Magic Mondays residency.
Booking lead time: 4\u20136 weeks (8\u201312 weeks peak season).
Contact: scott.syme@whiterabbitla.com \u2014 https://whiterabbitla.com`;
var brand_overview_default = defineTool2({
  name: "brand_overview",
  title: "Brand overview",
  description: "Returns a concise overview of White Rabbit LA \u2014 positioning, offerings, and contact info.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({ content: [{ type: "text", text: OVERVIEW }] })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "white-rabbit-la-mcp",
  title: "White Rabbit LA",
  version: "0.1.0",
  instructions: "Tools for the White Rabbit LA site. Use `echo` to verify connectivity and `brand_overview` for a concise brand summary.",
  tools: [echo_default, brand_overview_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
